events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /icons/ {
            alias /usr/share/nginx/html/icons/;
        }

        # Optional proxy to Streamlit if needed
        # location /streamlit/ {
        #     proxy_pass http://ui:8501/;
        # }
    }
}